import { Injectable } from '@angular/core';
import { Customer } from '../models/Customer';

@Injectable()
export class CustomerService {

  clients: Customer[] = [
    {
      _id: 1,
      name: 'John Miller',
      email: 'johnmiller@gmail.com',
      address: '55 Long Bridge Road',
      address2: '',
      city: 'Los Angeles',
      state: 'CA',
      zipcode: '78170',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 2,
      name: 'Samantha Rogers',
      email: 'samrogers@gmail.com',
      address: '55 River Way',
      address2: 'Apt 1001',
      city: 'London',
      zipcode: 'WC2N 5DU',
      country: 'United Kingdom',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 3,
      name: 'Paul Jacques',
      email: 'pauljacques@gmail.com',
      address: '55 Mounty Avenue',
      address2: '',
      city: 'Montreal',
      province: 'Quebec',
      zipcode: 'H1A 5R7',
      country: 'Canada',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 4,
      name: 'Norene O\'Kon',
      email: 'Arne20@yahoo.com',
      address: '35345 Rasheed Ville',
      address2: 'Apt. 661',
      city: 'Lake Green',
      state: 'IA',
      zipcode: '90926-5041',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 5,
      name: 'Mr. Allie Koss',
      email: 'Kaya3@yahoo.com',
      address: '342 Roberts Canyon',
      address2: 'Apt. 790',
      city: 'New Stanton',
      state: 'KS',
      zipcode: '04670',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 6,
      name: 'Dalton Stiedemann DVM',
      email: 'Jasen11@gmail.com',
      address: '83195 Bode Rapids',
      address2: 'Suite 401',
      city: 'South Albina',
      state: 'AR',
      zipcode: '47359',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 7,
      name: 'Mathias Daugherty III',
      email: 'Kian_Gleichner96@gmail.com',
      address: '011 Haylee Vista',
      address2: 'Suite 353',
      city: 'Prohaskashire',
      state: 'SD',
      zipcode: '22665-4380',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 8,
      name: 'Zoie Metz',
      email: 'Ezekiel_Hilpert87@hotmail.com',
      address: '86834 Kerluke Hills',
      address2: 'Apt. 456',
      city: 'South Antonietta',
      state: 'MS',
      zipcode: '40134-9211',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 9,
      name: 'Mylene Toy',
      email: 'Mathias89@yahoo.com',
      address: '0380 Mohr Throughway',
      address2: 'Suite 727',
      city: 'Delmerbury',
      state: 'CA',
      zipcode: '69386',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 10,
      name: 'Adell MacGyver',
      email: 'Graham81@hotmail.com',
      address: '13906 Klein Road',
      address2: 'Apt. 739',
      city: 'Lake Jamirview',
      state: 'ID',
      zipcode: '37757',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 11,
      name: 'Gladys Gleason',
      email: 'Alba.Olson72@yahoo.com',
      address: '7428 Weber Heights',
      address2: 'Apt. 844',
      city: 'Port Vida',
      state: 'RI',
      zipcode: '74055-9240',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 12,
      name: 'Bertram Borer',
      email: 'Molly.Bailey@yahoo.com',
      address: '76308 Casper Highway',
      address2: 'Suite 298',
      city: 'South Ned',
      state: 'ME',
      zipcode: '67200',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 13,
      name: 'Enid Champlin',
      email: 'Carmelo.Mraz@yahoo.com',
      address: '6689 Kelli Squares',
      address2: 'Suite 452',
      city: 'Bayerborough',
      state: 'NE',
      zipcode: '16942',
      country: 'United States',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 14,
      name: 'Erna Gutmann',
      email: 'Dimitri25@yahoo.com',
      address: '821 Hoeger Ville',
      address2: 'Suite 349',
      city: 'Port Dock',
      state: 'NC',
      zipcode: '35933',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 15,
      name: 'Brenden Walsh',
      email: 'Corrine.Waelchi49@hotmail.com',
      address: '170 Ewell Stream',
      address2: 'Apt. 000',
      city: 'Mandyport',
      state: 'MD',
      zipcode: '85655',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 16,
      name: 'Eleanore McGlynn',
      email: 'Clara_Halvorson@hotmail.com',
      address: '9733 Chaz Courts',
      address2: 'Suite 155',
      city: 'Lake Aric',
      state: 'AK',
      zipcode: '22215',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 17,
      name: 'Alexandria Feest',
      email: 'Michale24@hotmail.com',
      address: '311 Elwin Path',
      address2: 'Apt. 312',
      city: 'Reinholdborough',
      state: 'OK',
      zipcode: '33744-4552',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 18,
      name: 'Lazaro Macejkovic',
      email: 'Sadye.Green40@yahoo.com',
      address: '951 Hattie Isle',
      address2: 'Suite 462',
      city: 'Cummerataborough',
      state: 'WA',
      zipcode: '91678-1906',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 19,
      name: 'Kristian Schoen',
      email: 'Lydia43@yahoo.com',
      address: '81629 Vicky Hill',
      address2: 'Apt. 430',
      city: 'South Deangeloland',
      state: 'AL',
      zipcode: '46235',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 20,
      name: 'Geo Fisher',
      email: 'Amelie19@yahoo.com',
      address: '83277 Fernando Rapid',
      address2: 'Apt. 185',
      city: 'New Norbert',
      state: 'TX',
      zipcode: '93813-5110',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 21,
      name: 'Margaret Jaskolski',
      email: 'Fernando.Jast51@yahoo.com',
      address: '70874 Ashleigh Glens',
      address2: 'Apt. 403',
      city: 'North Fiona',
      state: 'NY',
      zipcode: '29337-5837',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 22,
      name: 'Shanie Abbott DDS',
      email: 'Mittie.Rutherford28@hotmail.com',
      address: '6222 Murazik Mountains',
      address2: 'Suite 973',
      city: 'Darrylborough',
      state: 'SC',
      zipcode: '11204',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 23,
      name: 'D\'angelo Kilback',
      email: 'Preston.Kemmer25@yahoo.com',
      address: '561 Bins Haven',
      address2: 'Apt. 344',
      city: 'East Anabelmouth',
      state: 'IL',
      zipcode: '70891-8957',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 24,
      name: 'Ms. Olin Leuschke',
      email: 'Nils_Shields@gmail.com',
      address: '41185 Olson Loop',
      address2: 'Suite 454',
      city: 'New Marleychester',
      state: 'HI',
      zipcode: '02508',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 25,
      name: 'Dr. Kaden Gerhold',
      email: 'Juvenal.Krajcik73@gmail.com',
      address: '216 Tobin Knolls',
      address2: 'Apt. 739',
      city: 'North Gianni',
      state: 'FL',
      zipcode: '18220-3320',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 26,
      name: 'Caitlyn Schmeler III',
      email: 'Anissa_Schamberger55@yahoo.com',
      address: '901 Selena Wall',
      address2: 'Suite 202',
      city: 'Mohammedport',
      state: 'AZ',
      zipcode: '77054',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 27,
      name: 'Kyleigh Rolfson',
      email: 'Damaris_Bogan76@gmail.com',
      address: '53356 Gleason Dam',
      address2: 'Suite 718',
      city: 'West Theaberg',
      state: 'SD',
      zipcode: '20483',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 28,
      name: 'Penelope Williamson',
      email: 'Eldred6@hotmail.com',
      address: '6922 Davin Road',
      address2: 'Apt. 396',
      city: 'New Janie',
      state: 'MA',
      zipcode: '57935',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 29,
      name: 'Michaela Tillman',
      email: 'Clifford_Gutmann@hotmail.com',
      address: '93514 Earnest Fields',
      address2: 'Suite 168',
      city: 'East Susana',
      state: 'PA',
      zipcode: '38154-8847',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 30,
      name: 'Nicolette Bechtelar',
      email: 'Alejandrin_Batz@yahoo.com',
      address: '9956 Reilly Parkways',
      address2: 'Apt. 212',
      city: 'Lonzostad',
      state: 'IA',
      zipcode: '84154',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 31,
      name: 'Kody Toy',
      email: 'Rudy.Wiegand67@yahoo.com',
      address: '1865 Emard Square',
      address2: 'Suite 468',
      city: 'Lake Joanietown',
      state: 'ME',
      zipcode: '30154-2844',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 32,
      name: 'Russel Hintz',
      email: 'Ramona99@gmail.com',
      address: '2152 Herman Place',
      address2: 'Suite 990',
      city: 'North Jeffryview',
      state: 'MS',
      zipcode: '70350-7125',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 33,
      name: 'Jerrod Yost',
      email: 'Lamar.Hansen58@hotmail.com',
      address: '3129 Candice Junction',
      address2: 'Apt. 623',
      city: 'North Abagailburgh',
      state: 'TX',
      zipcode: '03164',
      country: 'United States',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 34,
      name: 'Alessandro Gottlieb',
      email: 'Anabelle93@yahoo.com',
      address: '800 Alexander Ferry',
      address2: 'Apt. 685',
      city: 'New Bennettberg',
      state: 'OH',
      zipcode: '74161-2569',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 35,
      name: 'Samson Rath',
      email: 'Brando37@gmail.com',
      address: '7438 Wiza Parkway',
      address2: 'Apt. 074',
      city: 'West Caterina',
      state: 'ME',
      zipcode: '00419',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 36,
      name: 'Nathan Kunde',
      email: 'Emil_Konopelski@gmail.com',
      address: '63142 Fay Circles',
      address2: 'Suite 296',
      city: 'New Marcelle',
      state: 'NC',
      zipcode: '82972',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 37,
      name: 'Kelli Conn',
      email: 'Lorena.Shields46@hotmail.com',
      address: '58885 Spencer Burg',
      address2: 'Apt. 248',
      city: 'West Tarastad',
      state: 'KY',
      zipcode: '06708',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 38,
      name: 'Judge Von',
      email: 'Joanne81@yahoo.com',
      address: '37585 Hilpert Drives',
      address2: 'Suite 607',
      city: 'Juanitastad',
      state: 'IL',
      zipcode: '04377-8261',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 39,
      name: 'Maria Stanton',
      email: 'Janick_Torphy@hotmail.com',
      address: '9462 Hilpert Grove',
      address2: 'Apt. 683',
      city: 'Sporershire',
      state: 'NH',
      zipcode: '04092',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 40,
      name: 'Kariane Ullrich',
      email: 'Maeve95@gmail.com',
      address: '941 Antone Burgs',
      address2: 'Suite 047',
      city: 'New Babyport',
      state: 'OK',
      zipcode: '81532',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 41,
      name: 'Cordia Cormier',
      email: 'Heber39@yahoo.com',
      address: '054 Jazmin Shores',
      address2: 'Suite 177',
      city: 'North Heidistad',
      state: 'NY',
      zipcode: '95856-3277',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 42,
      name: 'Heather Grady',
      email: 'Graham97@yahoo.com',
      address: '5148 Sage Parks',
      address2: 'Suite 126',
      city: 'Lutherhaven',
      state: 'ME',
      zipcode: '50833',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 43,
      name: 'Trystan Johns',
      email: 'Xzavier.Upton@yahoo.com',
      address: '901 Herman Plain',
      address2: 'Suite 611',
      city: 'Rathberg',
      state: 'MD',
      zipcode: '94005-5801',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 44,
      name: 'Hayley Kassulke',
      email: 'Jada6@gmail.com',
      address: '563 Will Meadows',
      address2: 'Apt. 087',
      city: 'Lindsayland',
      state: 'MN',
      zipcode: '98029-7592',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 45,
      name: 'Dr. Turner Gutmann',
      email: 'Javier86@yahoo.com',
      address: '7035 Hallie Mills',
      address2: 'Apt. 253',
      city: 'East Helgabury',
      state: 'MD',
      zipcode: '61622',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 46,
      name: 'Buford Jaskolski',
      email: 'Caden_Wiza@yahoo.com',
      address: '89061 Quentin Plains',
      address2: 'Suite 923',
      city: 'Greentown',
      state: 'NY',
      zipcode: '48292-8829',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 47,
      name: 'Luigi Satterfield',
      email: 'Santina_Lubowitz79@gmail.com',
      address: '781 Magdalena Mall',
      address2: 'Apt. 589',
      city: 'Wiltonchester',
      state: 'WV',
      zipcode: '20540',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 48,
      name: 'Isaiah Frami',
      email: 'Irma.Ondricka@gmail.com',
      address: '384 Clay Plains',
      address2: 'Apt. 161',
      city: 'West Garnett',
      state: 'DE',
      zipcode: '56349',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 49,
      name: 'Rollin Ritchie',
      email: 'Summer.Lubowitz@hotmail.com',
      address: '61373 Alexandre Square',
      address2: 'Apt. 945',
      city: 'Walkerbury',
      state: 'MT',
      zipcode: '69687',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 50,
      name: 'Kelvin Flatley',
      email: 'Jasen.Bartoletti@hotmail.com',
      address: '204 Malinda Lodge',
      address2: 'Suite 068',
      city: 'East Mozelle',
      state: 'WY',
      zipcode: '29239',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 51,
      name: 'Ruthe Price',
      email: 'Selena.Stracke@yahoo.com',
      address: '90222 Rohan Walk',
      address2: 'Suite 481',
      city: 'Schillershire',
      state: 'VT',
      zipcode: '69121-7988',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 52,
      name: 'Otis Sipes',
      email: 'Sophie74@hotmail.com',
      address: '728 Rowena Shoals',
      address2: 'Suite 589',
      city: 'North Frida',
      state: 'IL',
      zipcode: '67655-2924',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 53,
      name: 'Hertha Dibbert',
      email: 'Ernestine.Trantow91@hotmail.com',
      address: '2434 Morissette Villages',
      address2: 'Apt. 000',
      city: 'Lake Don',
      state: 'NH',
      zipcode: '30585',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 54,
      name: 'Stephan Blanda',
      email: 'Maybell_Trantow@gmail.com',
      address: '65725 Lyla Harbors',
      address2: 'Apt. 313',
      city: 'Lednerside',
      state: 'CO',
      zipcode: '15826',
      country: 'United States',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 55,
      name: 'Mrs. Paul Douglas',
      email: 'Jefferey.Thompson@hotmail.com',
      address: '3734 Williamson Estate',
      address2: 'Apt. 768',
      city: 'Quitzonstad',
      state: 'MT',
      zipcode: '39607-0850',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 56,
      name: 'Kurtis Reilly',
      email: 'Garfield.Romaguera@yahoo.com',
      address: '7089 Rempel Mountains',
      address2: 'Apt. 701',
      city: 'South Orlohaven',
      state: 'AK',
      zipcode: '80761-7253',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 57,
      name: 'Rafael McDermott',
      email: 'Chester_Kulas18@yahoo.com',
      address: '072 Bernadine Lake',
      address2: 'Apt. 421',
      city: 'Zemlakstad',
      state: 'IA',
      zipcode: '12599',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 58,
      name: 'Jaylen Doyle',
      email: 'Elinore42@yahoo.com',
      address: '5742 Vandervort Locks',
      address2: 'Suite 675',
      city: 'North Emmetttown',
      state: 'NV',
      zipcode: '10222-8270',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 59,
      name: 'Vena Mueller',
      email: 'Rodolfo83@hotmail.com',
      address: '855 Emmanuel Walk',
      address2: 'Apt. 141',
      city: 'Darrelchester',
      state: 'VA',
      zipcode: '35330-8356',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 60,
      name: 'Prudence Weimann',
      email: 'Devonte.Cummerata99@hotmail.com',
      address: '7236 Prudence Hollow',
      address2: 'Apt. 564',
      city: 'Ianport',
      state: 'MT',
      zipcode: '84713',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 61,
      name: 'Adalberto Kulas',
      email: 'Russ.Brekke@hotmail.com',
      address: '7766 Fernando Way',
      address2: 'Apt. 254',
      city: 'Port Jamaalbury',
      state: 'MN',
      zipcode: '37678-4372',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 62,
      name: 'Heaven Nienow',
      email: 'Elwin_Langworth99@gmail.com',
      address: '31924 Neoma Viaduct',
      address2: 'Apt. 376',
      city: 'Lake Alexys',
      state: 'CO',
      zipcode: '46271-3923',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 63,
      name: 'Alexandro Hyatt',
      email: 'Doris_Pfannerstill93@hotmail.com',
      address: '36495 Chasity Valley',
      address2: 'Suite 362',
      city: 'Giovannymouth',
      state: 'NH',
      zipcode: '47221-4503',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 64,
      name: 'Camden Kessler',
      email: 'Bethel71@gmail.com',
      address: '90225 Gorczany Lodge',
      address2: 'Suite 655',
      city: 'East Cortney',
      state: 'ND',
      zipcode: '35675-9836',
      country: 'United States',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 65,
      name: 'Johanna Kuhlman',
      email: 'Skyla97@hotmail.com',
      address: '01344 Bednar Flats',
      address2: 'Apt. 338',
      city: 'Port Kaylinshire',
      state: 'UT',
      zipcode: '43576',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 66,
      name: 'Sophie Cormier',
      email: 'Aileen_Rutherford@gmail.com',
      address: '122 Noemi Summit',
      address2: 'Suite 043',
      city: 'Marquesberg',
      state: 'LA',
      zipcode: '92275',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 67,
      name: 'Jeanette Eichmann',
      email: 'Dewitt_Anderson@gmail.com',
      address: '104 Sidney Loop',
      address2: 'Suite 097',
      city: 'Port Charitytown',
      state: 'TX',
      zipcode: '65181',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 68,
      name: 'Arden Tromp',
      email: 'River.Bauch96@yahoo.com',
      address: '4431 Idella Hollow',
      address2: 'Suite 351',
      city: 'Port Jesus',
      state: 'SD',
      zipcode: '64938',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 69,
      name: 'Mae Farrell',
      email: 'Aiyana_Bechtelar@gmail.com',
      address: '4706 Cruickshank Point',
      address2: 'Apt. 223',
      city: 'Kutchside',
      state: 'MA',
      zipcode: '57065',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 70,
      name: 'Yesenia Herzog',
      email: 'Kathlyn38@gmail.com',
      address: '305 Bette River',
      address2: 'Suite 206',
      city: 'Port Ledamouth',
      state: 'FL',
      zipcode: '73194-4578',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 71,
      name: 'Roxane Goodwin',
      email: 'Polly_Labadie@yahoo.com',
      address: '1552 Pagac Shoal',
      address2: 'Suite 966',
      city: 'Ernieport',
      state: 'RI',
      zipcode: '74510',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 72,
      name: 'Valentine Koepp',
      email: 'Annamae.Howell38@hotmail.com',
      address: '2291 Heloise Shoal',
      address2: 'Suite 064',
      city: 'Hipolitofurt',
      state: 'VT',
      zipcode: '54677',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 73,
      name: 'Dr. Mose Rempel',
      email: 'Lenora40@gmail.com',
      address: '08437 Prohaska Roads',
      address2: 'Suite 372',
      city: 'East Delmer',
      state: 'WV',
      zipcode: '53555-7705',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 74,
      name: 'Rosalinda Hoppe',
      email: 'Lizeth_Nienow29@hotmail.com',
      address: '657 Roberts Stream',
      address2: 'Apt. 470',
      city: 'Sallieside',
      state: 'CO',
      zipcode: '44703',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 75,
      name: 'Litzy Volkman',
      email: 'Wilson_Lindgren@hotmail.com',
      address: '50339 King Dam',
      address2: 'Suite 757',
      city: 'West Fatima',
      state: 'MO',
      zipcode: '30988',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 76,
      name: 'Maribel Reinger',
      email: 'Noemy_Baumbach80@hotmail.com',
      address: '732 Vinnie Lakes',
      address2: 'Suite 514',
      city: 'West Daisyborough',
      state: 'MS',
      zipcode: '15279-5713',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 77,
      name: 'Mrs. Simeon Stoltenberg',
      email: 'George40@yahoo.com',
      address: '8462 Crawford Summit',
      address2: 'Suite 415',
      city: 'South Cyrilchester',
      state: 'OK',
      zipcode: '87012-5498',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 78,
      name: 'Rhett Kihn',
      email: 'Luciano43@yahoo.com',
      address: '323 Rosenbaum Corners',
      address2: 'Suite 502',
      city: 'Lake Zion',
      state: 'TX',
      zipcode: '60846',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 79,
      name: 'Ms. Melyssa Toy',
      email: 'Irma_Denesik@yahoo.com',
      address: '883 Rusty Course',
      address2: 'Apt. 435',
      city: 'New Zariafort',
      state: 'OK',
      zipcode: '26511',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 80,
      name: 'Ceasar Altenwerth',
      email: 'Shanie_Marquardt@gmail.com',
      address: '22759 Giles Brook',
      address2: 'Apt. 972',
      city: 'South Medamouth',
      state: 'MN',
      zipcode: '23599-9041',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 81,
      name: 'Foster Eichmann',
      email: 'Ashley.Christiansen@gmail.com',
      address: '879 Brooks Loaf',
      address2: 'Suite 462',
      city: 'Claudineburgh',
      state: 'AL',
      zipcode: '57011',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 82,
      name: 'Susan McGlynn',
      email: 'Libbie_Mayert@hotmail.com',
      address: '5162 Aurelie Inlet',
      address2: 'Apt. 536',
      city: 'Port Zacheryside',
      state: 'AR',
      zipcode: '30361-2448',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 83,
      name: 'Nathan Ziemann',
      email: 'Rupert_Hyatt89@gmail.com',
      address: '30527 Wolff Rapid',
      address2: 'Suite 996',
      city: 'Port Hunter',
      state: 'MD',
      zipcode: '43408',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 84,
      name: 'Reyes Bernhard',
      email: 'Greg41@yahoo.com',
      address: '03795 Elwin Forge',
      address2: 'Apt. 015',
      city: 'Doylechester',
      state: 'UT',
      zipcode: '05895',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 85,
      name: 'Karli Wyman',
      email: 'Elias_Connelly26@gmail.com',
      address: '6968 Cassandre Oval',
      address2: 'Apt. 070',
      city: 'West Micheal',
      state: 'ID',
      zipcode: '29408-4573',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 86,
      name: 'Frieda Gleichner Jr.',
      email: 'Allie.Kohler@hotmail.com',
      address: '38873 Donnelly Garden',
      address2: 'Suite 139',
      city: 'East Montana',
      state: 'SC',
      zipcode: '31600-6888',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 87,
      name: 'Mr. Alvis Hoeger',
      email: 'Vergie13@yahoo.com',
      address: '0200 Bobbie Lakes',
      address2: 'Suite 871',
      city: 'North Korey',
      state: 'NJ',
      zipcode: '79041',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 88,
      name: 'Alvina Casper',
      email: 'Nora31@gmail.com',
      address: '40672 Jordyn Roads',
      address2: 'Suite 767',
      city: 'Osinskiberg',
      state: 'TN',
      zipcode: '33294',
      country: 'United States',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 89,
      name: 'Dameon Heaney',
      email: 'Leonard36@yahoo.com',
      address: '90251 Rosella Motorway',
      address2: 'Apt. 719',
      city: 'Zulaufmouth',
      state: 'OK',
      zipcode: '15554',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 90,
      name: 'Ms. Kacie Koelpin',
      email: 'Baby.Grant@yahoo.com',
      address: '5157 Bode Fords',
      address2: 'Suite 665',
      city: 'Kalebburgh',
      state: 'MO',
      zipcode: '64964-9771',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 91,
      name: 'Cornelius Hermiston',
      email: 'Tessie_Sporer69@yahoo.com',
      address: '22155 Rosemarie Brook',
      address2: 'Suite 358',
      city: 'Langoshside',
      state: 'DE',
      zipcode: '82321',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 92,
      name: 'Asia Powlowski',
      email: 'Geo.Schiller@yahoo.com',
      address: '245 Dooley Rue',
      address2: 'Apt. 801',
      city: 'Soledadchester',
      state: 'NM',
      zipcode: '44609',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 93,
      name: 'Wilfrid Schumm',
      email: 'Sister.Jakubowski35@yahoo.com',
      address: '70604 Gorczany Walk',
      address2: 'Suite 648',
      city: 'Sanfordmouth',
      state: 'GA',
      zipcode: '41534-0070',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 94,
      name: 'Joyce Mayert',
      email: 'Vilma.Grady68@gmail.com',
      address: '86706 Karlee Bypass',
      address2: 'Apt. 780',
      city: 'Vonberg',
      state: 'ID',
      zipcode: '25279-6406',
      country: 'United States',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 95,
      name: 'Nola Harber',
      email: 'Eldora.Brakus25@hotmail.com',
      address: '6879 Beahan Parkway',
      address2: 'Apt. 638',
      city: 'South Tiaburgh',
      state: 'ND',
      zipcode: '91449',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 96,
      name: 'Jaylan Lind',
      email: 'Deborah62@gmail.com',
      address: '066 Gaylord Summit',
      address2: 'Suite 410',
      city: 'New Laurenceshire',
      state: 'ND',
      zipcode: '49565-3580',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 97,
      name: 'Terrance Doyle',
      email: 'Nicklaus.Yundt@yahoo.com',
      address: '832 Davonte Overpass',
      address2: 'Suite 891',
      city: 'East Austinmouth',
      state: 'MS',
      zipcode: '76629-9347',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 98,
      name: 'Jessika Anderson Sr.',
      email: 'Zoie_Luettgen@yahoo.com',
      address: '834 Reina Ranch',
      address2: 'Suite 860',
      city: 'Kesslerberg',
      state: 'MT',
      zipcode: '46540-5574',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 99,
      name: 'Waino Jast',
      email: 'Korbin_Haag54@gmail.com',
      address: '37864 Yadira Summit',
      address2: 'Apt. 446',
      city: 'Krisville',
      state: 'IN',
      zipcode: '90700',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 100,
      name: 'Brett Dibbert',
      email: 'Ed21@hotmail.com',
      address: '7427 Zieme Squares',
      address2: 'Suite 324',
      city: 'Nettietown',
      state: 'MT',
      zipcode: '77213-6379',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 101,
      name: 'Mr. Werner Rempel',
      email: 'Arjun_Wilderman@hotmail.com',
      address: '419 Nienow Shoals',
      address2: 'Suite 970',
      city: 'South Watsontown',
      state: 'WV',
      zipcode: '99122',
      country: 'United States',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 102,
      name: 'Mr. Hilbert Keebler',
      email: 'Frieda76@yahoo.com',
      address: '97055 Nicholaus Flat',
      address2: 'Suite 574',
      city: 'O\'Connershire',
      state: 'IA',
      zipcode: '18531-5704',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 103,
      name: 'Nasir Hand',
      email: 'Nathen.Brakus33@yahoo.com',
      address: '51464 Romaine Knoll',
      address2: 'Apt. 969',
      city: 'Lempiport',
      state: 'DE',
      zipcode: '69082',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 104,
      name: 'Jensen Bernhard',
      email: 'Jo_Kunde14@hotmail.com',
      address: '67365 Nienow Place',
      address2: 'Apt. 561',
      city: 'New Linneafurt',
      state: 'RI',
      zipcode: '58244',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 105,
      name: 'Ashley Hegmann',
      email: 'Lou.Kuvalis63@yahoo.com',
      address: '437 Demetrius Fords',
      address2: 'Apt. 474',
      city: 'Lucyfurt',
      state: 'MN',
      zipcode: '09815-7275',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 106,
      name: 'Cristopher Bernier',
      email: 'Burnice_Jerde@yahoo.com',
      address: '4947 Savanah Islands',
      address2: 'Suite 800',
      city: 'West Leonorborough',
      state: 'MS',
      zipcode: '55341-2186',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 107,
      name: 'Scarlett Grimes',
      email: 'Mireille61@gmail.com',
      address: '285 Nedra Center',
      address2: 'Apt. 904',
      city: 'Hermanborough',
      state: 'WV',
      zipcode: '19967',
      country: 'United States',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 108,
      name: 'Cornell Raynor',
      email: 'Emilio_Bechtelar@yahoo.com',
      address: '900 Eda Way',
      address2: 'Suite 019',
      city: 'South Harleymouth',
      state: 'MA',
      zipcode: '83791',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 109,
      name: 'Modesta Crist',
      email: 'Johann.Wiza71@gmail.com',
      address: '01038 Gusikowski Curve',
      address2: 'Apt. 023',
      city: 'Lake Lucious',
      state: 'DE',
      zipcode: '26254',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 110,
      name: 'Dejon Deckow Sr.',
      email: 'Matilda_Mohr78@yahoo.com',
      address: '35084 Amina Viaduct',
      address2: 'Apt. 790',
      city: 'West Lurlineborough',
      state: 'TN',
      zipcode: '81567',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 111,
      name: 'Rhoda Schaefer',
      email: 'Diana_Robel@gmail.com',
      address: '32028 Lynch Skyway',
      address2: 'Suite 510',
      city: 'Port Kingland',
      state: 'WY',
      zipcode: '41211',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 112,
      name: 'Watson Bruen III',
      email: 'Adah.Bartoletti38@hotmail.com',
      address: '36298 Antwon Vista',
      address2: 'Suite 589',
      city: 'Cristchester',
      state: 'IA',
      zipcode: '77641-8042',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 113,
      name: 'Kacie Morissette',
      email: 'Garnet62@hotmail.com',
      address: '377 Hodkiewicz Flats',
      address2: 'Suite 258',
      city: 'Schmelerfort',
      state: 'NJ',
      zipcode: '78045',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 114,
      name: 'Mohammed Reichert',
      email: 'Giles65@gmail.com',
      address: '75225 Burdette Dale',
      address2: 'Suite 437',
      city: 'South Bradleychester',
      state: 'WI',
      zipcode: '95475-3551',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 115,
      name: 'Aric Brekke',
      email: 'Selmer39@yahoo.com',
      address: '075 Cummings Burgs',
      address2: 'Suite 918',
      city: 'Alfredaberg',
      state: 'MD',
      zipcode: '90893',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 116,
      name: 'Jenifer McKenzie',
      email: 'Johnpaul53@gmail.com',
      address: '6079 Mikayla Locks',
      address2: 'Suite 975',
      city: 'Labadieland',
      state: 'NC',
      zipcode: '54924-5593',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 117,
      name: 'Marcellus Runte',
      email: 'Bettye_Wiegand@gmail.com',
      address: '75201 Brooklyn Gardens',
      address2: 'Apt. 593',
      city: 'Gerlachfurt',
      state: 'OH',
      zipcode: '70756-6067',
      country: 'United States',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 118,
      name: 'Grant Greenfelder',
      email: 'Ebba_Moore44@hotmail.com',
      address: '4305 Glover Oval',
      address2: 'Suite 453',
      city: 'West Veronaland',
      state: 'NM',
      zipcode: '21165',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 119,
      name: 'Ms. Kasandra Hand',
      email: 'Isabell.Huels@yahoo.com',
      address: '49926 Marlon Lodge',
      address2: 'Suite 430',
      city: 'Ornton',
      state: 'NV',
      zipcode: '96944',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 120,
      name: 'Garth Ward',
      email: 'Destin42@yahoo.com',
      address: '6066 Jacobs Wall',
      address2: 'Apt. 034',
      city: 'Lake Courtneymouth',
      state: 'MI',
      zipcode: '81561',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 121,
      name: 'Webster Kohler',
      email: 'Berenice9@gmail.com',
      address: '7193 Johnston Trafficway',
      address2: 'Apt. 849',
      city: 'Cruickshankview',
      state: 'AR',
      zipcode: '90132-5897',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 122,
      name: 'Kennedi Brekke',
      email: 'Jacky53@hotmail.com',
      address: '3892 Balistreri Square',
      address2: 'Apt. 784',
      city: 'West Frederic',
      state: 'ID',
      zipcode: '46730',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 123,
      name: 'Chelsea Kiehn',
      email: 'Josh.Champlin@gmail.com',
      address: '8708 Senger Groves',
      address2: 'Suite 474',
      city: 'Lake Wilhelmine',
      state: 'MO',
      zipcode: '60663-8504',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 124,
      name: 'Catherine Conroy',
      email: 'Cristina.Beahan@gmail.com',
      address: '7099 Kreiger Ramp',
      address2: 'Apt. 235',
      city: 'New Naomie',
      state: 'MA',
      zipcode: '87594-5299',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 125,
      name: 'Dillon Larkin',
      email: 'Bret89@hotmail.com',
      address: '23351 Smitham Overpass',
      address2: 'Apt. 327',
      city: 'Darianaton',
      state: 'IN',
      zipcode: '98745',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 126,
      name: 'Shaylee Boyle',
      email: 'Ibrahim58@hotmail.com',
      address: '6031 Marshall Trace',
      address2: 'Apt. 826',
      city: 'Port Zetta',
      state: 'CT',
      zipcode: '46217-8576',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 127,
      name: 'Stephan Prohaska',
      email: 'Hilma_Blick@gmail.com',
      address: '9995 Giles Plaza',
      address2: 'Apt. 736',
      city: 'North Adella',
      state: 'AL',
      zipcode: '20876-0649',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 128,
      name: 'Gloria Veum',
      email: 'Rosalinda.Gottlieb@hotmail.com',
      address: '972 Rhett Spring',
      address2: 'Suite 422',
      city: 'West Vernfurt',
      state: 'MI',
      zipcode: '67659',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 129,
      name: 'Robb Runte',
      email: 'Erika_Kuphal81@hotmail.com',
      address: '570 Nitzsche Rue',
      address2: 'Suite 141',
      city: 'Port Jules',
      state: 'IL',
      zipcode: '37606-5701',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 130,
      name: 'Deborah Conn',
      email: 'Preston_Strosin@yahoo.com',
      address: '798 Halvorson Shoals',
      address2: 'Suite 147',
      city: 'Danafort',
      state: 'CT',
      zipcode: '28681',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 131,
      name: 'Clint Cole',
      email: 'Trystan_Kling@gmail.com',
      address: '80178 Sim Port',
      address2: 'Suite 271',
      city: 'Lake Dixie',
      state: 'VT',
      zipcode: '92018',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 132,
      name: 'Elaina Herman II',
      email: 'Jarred74@gmail.com',
      address: '1500 Runolfsdottir Prairie',
      address2: 'Apt. 480',
      city: 'Hilpertside',
      state: 'NC',
      zipcode: '12288',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 133,
      name: 'Dahlia Dickinson',
      email: 'Suzanne_Langworth@hotmail.com',
      address: '738 Friesen Manors',
      address2: 'Suite 644',
      city: 'New Rosie',
      state: 'PA',
      zipcode: '74051-4936',
      country: 'United States',
      totalOrders: 3,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 134,
      name: 'Lynn Price',
      email: 'Sylvia.Murray1@hotmail.com',
      address: '017 Margarett Islands',
      address2: 'Apt. 296',
      city: 'Agustinaport',
      state: 'MO',
      zipcode: '69054',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 135,
      name: 'Dr. Chasity Schinner',
      email: 'Michelle.Johnson@hotmail.com',
      address: '394 Elvis Lane',
      address2: 'Suite 629',
      city: 'Dewittbury',
      state: 'AR',
      zipcode: '91463',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 136,
      name: 'Zula Powlowski MD',
      email: 'Kaleb_Hansen80@gmail.com',
      address: '9902 Fahey Extension',
      address2: 'Apt. 497',
      city: 'East Matt',
      state: 'GA',
      zipcode: '04067',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 137,
      name: 'Javonte Witting',
      email: 'Henriette_Boyle@gmail.com',
      address: '25726 Mitchell Common',
      address2: 'Apt. 453',
      city: 'Sierraton',
      state: 'NE',
      zipcode: '25011',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 138,
      name: 'Keshawn Macejkovic',
      email: 'Magnus_Ward37@gmail.com',
      address: '7377 Pattie Vista',
      address2: 'Suite 149',
      city: 'South Jillian',
      state: 'NC',
      zipcode: '90016-9158',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 139,
      name: 'Gabe Barrows',
      email: 'Laisha.Leuschke@gmail.com',
      address: '15166 Grimes Port',
      address2: 'Apt. 512',
      city: 'South Holliston',
      state: 'MN',
      zipcode: '27747',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 140,
      name: 'Alex Gleichner',
      email: 'Precious_Lebsack95@hotmail.com',
      address: '870 Daugherty Stravenue',
      address2: 'Suite 932',
      city: 'Odabury',
      state: 'CA',
      zipcode: '97381',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 141,
      name: 'Madonna Collier',
      email: 'Loyal18@gmail.com',
      address: '1707 Shyann Drive',
      address2: 'Apt. 593',
      city: 'Zboncakport',
      state: 'AZ',
      zipcode: '40611',
      country: 'United States',
      totalOrders: 8,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 142,
      name: 'Miss Reyna Monahan',
      email: 'Carole_Schinner42@hotmail.com',
      address: '8590 Graham Lane',
      address2: 'Suite 451',
      city: 'Framihaven',
      state: 'AL',
      zipcode: '05366-5686',
      country: 'United States',
      totalOrders: 2,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 143,
      name: 'Julio Green V',
      email: 'Ressie.Jakubowski@yahoo.com',
      address: '1088 Corkery Mall',
      address2: 'Suite 433',
      city: 'Ardellatown',
      state: 'TN',
      zipcode: '37785',
      country: 'United States',
      totalOrders: 6,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 144,
      name: 'Harrison Schumm',
      email: 'Christophe.Beer@yahoo.com',
      address: '7842 Lilla Islands',
      address2: 'Suite 031',
      city: 'East Nathen',
      state: 'MD',
      zipcode: '31060-2348',
      country: 'United States',
      totalOrders: 1,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 145,
      name: 'Deontae Kreiger',
      email: 'Hellen97@gmail.com',
      address: '38492 Renner Spring',
      address2: 'Apt. 932',
      city: 'Robertsland',
      state: 'TX',
      zipcode: '61313-9341',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 146,
      name: 'Brenna Mertz',
      email: 'Johann_Haag41@gmail.com',
      address: '66306 Emmerich Falls',
      address2: 'Apt. 679',
      city: 'West Corrine',
      state: 'ME',
      zipcode: '80998',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 147,
      name: 'Alessandro Predovic',
      email: 'Lora7@hotmail.com',
      address: '188 Bailey Trail',
      address2: 'Apt. 350',
      city: 'East Bryanahaven',
      state: 'CA',
      zipcode: '69926-6136',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 148,
      name: 'Greg Jaskolski',
      email: 'Ruth.Wisozk@yahoo.com',
      address: '7146 West Station',
      address2: 'Suite 734',
      city: 'Tyreeview',
      state: 'NH',
      zipcode: '53242',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 149,
      name: 'Marjory Kuhn',
      email: 'Rhiannon.Swift51@hotmail.com',
      address: '533 Rempel Expressway',
      address2: 'Apt. 983',
      city: 'Rowetown',
      state: 'HI',
      zipcode: '85055-5069',
      country: 'United States',
      totalOrders: 5,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 150,
      name: 'Mr. Velda Larson',
      email: 'Ludie_Mayer@hotmail.com',
      address: '3406 Roberts Heights',
      address2: 'Apt. 394',
      city: 'Kayleyfort',
      state: 'NM',
      zipcode: '45451',
      country: 'United States',
      totalOrders: 7,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 151,
      name: 'Mr. Jayda Hoeger',
      email: 'Kaycee_Bartoletti@yahoo.com',
      address: '874 Dejah Orchard',
      address2: 'Suite 832',
      city: 'Port Edbury',
      state: 'AL',
      zipcode: '35570-2080',
      country: 'United States',
      totalOrders: 9,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 152,
      name: 'Maggie Stanton',
      email: 'Camren99@hotmail.com',
      address: '4203 Cydney Vista',
      address2: 'Apt. 191',
      city: 'Lake Wilbertfort',
      state: 'MN',
      zipcode: '37353-7303',
      country: 'United States',
      totalOrders: 4,
      imageURL: '../../assets/images/customers/avatar.png'
    },
    {
      _id: 153,
      name: 'Kaleb Crooks',
      email: 'Tommie58@gmail.com',
      address: '2403 Kautzer Inlet',
      address2: 'Apt. 639',
      city: 'Lake Jerrodchester',
      state: 'CA',
      zipcode: '97048',
      country: 'United States',
      totalOrders: 10,
      imageURL: '../../assets/images/customers/avatar.png'
    }
  ];

  constructor() { }

  getCustomers(): Customer[] {
    return this.clients;
  }

}
